# Site settings
title: Hi, I am Ashwin
email: public.ashwinsreevatsa@gmail.com
url: https://example.github.io
description: "I am a student that the University of Michigan studying computer science. I like to build stuff."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Ashwin Sreevatsa

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/TheAshwinner
  - title: stack-overflow
    url: https://stackoverflow.com/users/10256672/ashwin-sreevatsa?tab=profile
  - title: github
    url: https://github.com/TheAshwinner
  - title: linkedin
    url: https://www.linkedin.com/in/ashwinsreevatsa/
# Build settings
markdown: kramdown
permalink: pretty
